#!/bin/bash
set -e
cd `dirname $0`

if [[ ( i2cztest2.armv7l -ot i2cztest2.cc ) || ( i2cztest2.armv7l -ot i2czlib.cc ) ]]
then
    set -x
    g++ -g -Wall -o i2cztest2.armv7l i2cztest2.cc i2czlib.cc lib.armv7l.a
    set +x
fi

./loadmod.sh

dbg=
if [ "$1" == "-gdb" ]
then
    dbg='gdb --args'
    shift
fi
exec $dbg ./i2cztest2.armv7l "$@"
