#!/bin/bash
set -e
cd `dirname $0`

if [ i2cztest.armv7l -ot i2cztest.cc ]
then
    g++ -g -o i2cztest.armv7l i2cztest.cc lib.armv7l.a
fi

if grep -q 'Xilinx Zynq' /proc/cpuinfo
then
    if ! lsmod | grep -q ^zynqpdp8l
    then
        if [ ! -f km-zynqpdp8l/zynqpdp8l.`uname -r`.ko ]
        then
            cd km-zynqpdp8l
            rm -f zynqpdp8l.ko zynqpdp8l.mod* zynqpdp8l.o modules.order Module.symvers .zynqpdp8l* .modules* .Module*
            make
            mv zynqpdp8l.ko zynqpdp8l.`uname -r`.ko
            cd ..
        fi
        sudo insmod km-zynqpdp8l/zynqpdp8l.`uname -r`.ko
    fi
    if ! lsmod | grep -q ^enabtsc
    then
        if [ ! -f km-enabtsc/enabtsc.`uname -r`.ko ]
        then
            cd km-enabtsc
            rm -f enabtsc.ko enabtsc.mod* enabtsc.o modules.order Module.symvers .enabtsc* .modules* .Module*
            make
            mv enabtsc.ko enabtsc.`uname -r`.ko
            cd ..
        fi
        sudo insmod km-enabtsc/enabtsc.`uname -r`.ko
    fi
fi

dbg=
if [ "$1" == "-gdb" ]
then
    dbg='gdb --args'
    shift
fi
exec $dbg ./i2cztest.armv7l "$@"
