#!/bin/bash
#
#  Start z8lpin on the zturn board programmed with the PDP-8/L simulator
#
dd=`dirname $0`
$dd/loadmod.sh
export z8lpinini=$dd/z8lpinini.tcl
dbg=
if [ "$1" == "-gdb" ]
then
    dbg='-gdb'
    shift
fi
exec ./z8lpin.`uname -m` $dbg "$@"
