#!/bin/bash
#
#  Start pipan8l on the zturn board programmed with the PDP-8/L simulator
#
dd=`dirname $0`
$dd/loadmod.sh
export pipan8lini=$dd/z8lsimini.tcl
dbg=
if [ "$1" == "-gdb" ]
then
    dbg='-gdb'
    shift
fi
exec ./pipan8l $dbg -z8l "$@"
